### ISSUE TITLE
Help with URL patterns

### ISSUE THREAD

**Issue by beefwellington13** [codelibs/elasticsearch-river-web#116]
Attached below is my current crawler config and I have a few questions about the URL patterns.

I have a "Support Training" page that has 10 links to other .aspx pages that contain links to PDFs on them. However, not all 10 of the links on the "Support Training" page are crawled. I tried to show this below. The "itsp.aspx" and "documentation.aspx" pages are both linked from the main "Support Training" page. Any idea why some PDFs are index but not others?

(here's a picture of the text below since github messes up the format: [http://i.imgur.com/FREWgGa.png](http://i.imgur.com/FREWgGa.png))

1. https://mysite.com/support_training/support_training_overview.aspx
  A. https://mysite.com/support_training/itsp.aspx (No Scraping Rule)
    A1. https://mysite.com/documents/support_training/itsp_appnotes/document1.pdf (Doesn't get index)
    A2. https://mysite.com/documents/support_training/itsp_appnotes/document2.pdf (Doesn't get index)
    A3. https://mysite.com/documents/support_training/itsp_appnotes/document3.pdf (Doesn't get index)
    A4. https://mysite.com/documents/support_training/itsp_appnotes/document4.pdf (Doesn't get index)
  B. https://mysite.com/support_training/documentation.aspx (Gets crawled)
    B1. https://mysite.com/documents/support_training/publications/ReleaseNotes/Server/document1.pdf (Gets indexed)
    B2. https://mysite.com/documents/support_training/publications/ReleaseNotes/Server/document2.pdf (Gets indexed)
    B3. https://mysite.com/documents/support_training/publications/ReleaseNotes/Server/document3.pdf (Gets indexed)
    B4. https://mysite.com/documents/support_training/publications/ReleaseNotes/Server/document4.pdf (Gets indexed)

```{
    "index" : "index_mysite_web",
    "type" : "type_mysite_web",
    "url" : ["https://mysite.com/default.aspx"],
    "includeFilter" : ["https://mysite.com/.*", "https://mysite.com/support_training/*", "https://na13.salesforce.com/_ui/selfservice/pkb/PublicKnowledgeSolution/*"],
    "excludeFilter" : ["https://mysite.com/.*(?:png|jpg|jpeg|gif|css|js|axd|zip|tgz|tar|gz|bz)"],
    "maxDepth" : 10,
    "maxAccessCount" : 100,
    "numOfThread" : 10,
    "interval" : 1000,
    "overwrite" : true,
    "robotsTxt" : true,
    "userAgent" : "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1",
    "target" : [
      {
        "settings" : {
          "html" : false
        },
        "pattern" : {
          "url" : "https://mysite.com/documents/.*pdf",
          "mimeType" : "application/pdf"
        },
        "properties": {
            "file": {
                "type": "attachment",
                "maxFileSize" : 9000000000000000000
            }
        }
      },
      {
        "settings" : {
          "html" : false
        },
        "pattern" : {
          "url" : "https://mysite.com/documents/.*doc",
          "mimeType" : "application/msword"
        },
        "properties": {
            "file": {
                "type": "attachment",
                "maxFileSize" : 9000000000000000000
            }
        }
      },
      {
        "settings" : {
          "html" : false
        },
        "pattern" : {
          "url" : "https://mysite.com/documents/.*docx",
          "mimeType" : "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        },
        "properties": {
            "file": {
                "type": "attachment",
                "maxFileSize" : 9000000000000000000
            }
        }
      },
      {
        "settings" : {
          "html" : false
        },
        "pattern" : {
          "url" : "https://na13.salesforce.com/_ui/selfservice/pkb/PublicKnowledgeSolution/d",
          "mimeType" : "text/html"
        },
        "properties": {
            "title": {
                "text": ".solutionTitleDetail"
            },
            "body": {
                "text": ".solutionBodyDetail"
            }
        }
      },
      {
        "settings" : {
          "html" : false
        },
        "pattern" : {
          "url" : "https://mysite.com/support_training/rma/rma_submission.aspx",
          "mimeType" : "text/html"
        },
        "properties": {
            "title": {
                "text": ".headerBar p"
            },
            "body": {
                "text": "#portal_content"
            }
        }
      }
    ]
}```

**Comment by marevol** [comment]
Please check a log file after changing to debug level in config/log4j.xml.

**Comment by beefwellington13** [comment]
so my issue was, maxAccessCount was set to "100" which it was reaching so it never scraped the page I posted about.
