### ISSUE TITLE
URL with Parameters

### ISSUE THREAD

**Issue by marvink** [codelibs/elasticsearch-river-web#99]
Hi i've trying to ignore all URL with some specific URL Parameters for Pagination e.g. sort=, q=, page=, pageSize= All URL are starting with the query parameter so maybe i can ignore all urls with a beginning query parameter.

How can i handle this?
Which wildcards can i use in the include or excludeFilters?

"includeFilter" : ["http://www.url.ch/outdoor/.*"],	
"excludeFilter" : ["http://www.url.ch/outdoor/.*?.*"],

**Comment by marevol** [comment]
includeFilter and excludeFilter process a value as Java regexp.
? needs to be escaped.
